### ISSUE TITLE
Github Actions windows test failed due to conflict

### ISSUE THREAD

**Issue by ErdemOzgen** [ErdemOzgen/recording-angel#20]
```YAML
jobs:
  tests:
    name: ${{ matrix.session }} ${{ matrix.python }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python: "3.10", os: "ubuntu-latest", session: "pre-commit" }
          - { python: "3.10", os: "ubuntu-latest", session: "safety" }
          - { python: "3.10", os: "ubuntu-latest", session: "mypy" }
          - { python: "3.9", os: "ubuntu-latest", session: "mypy" }
          - { python: "3.10", os: "ubuntu-latest", session: "tests" }
          - { python: "3.9", os: "ubuntu-latest", session: "tests" }
          # - { python: "3.10", os: "windows-latest", session: "tests" }
          - { python: "3.10", os: "macos-latest", session: "tests" }
          - { python: "3.10", os: "ubuntu-latest", session: "typeguard" }
          - { python: "3.10", os: "ubuntu-latest", session: "xdoctest" }
          - { python: "3.10", os: "ubuntu-latest", session: "docs-build" }
 ```

Currently just comment out line but needs to take care
